version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - action.destructive_requires_name=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - transport.host= 0.0.0.0
      - http.host= 0.0.0.0
      - discovery.zen.minimum_master_nodes= 1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      net_es:
        ipv4_address: 172.29.1.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      I18N_LOCALE: fr-FR
    restart: always
    ports:
      - "5601:5601"
    networks:
      net_es:
        ipv4_address: 172.29.1.3
    depends_on:
      - elasticsearch
networks:
  net_es:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16