version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      net_kafka_nifi:
        ipv4_address: 172.21.0.9

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      ALLOW_ANONYMOUS_LOGIN : yes
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      BOOTSTRAP_SERVERS: kafka1:9092
    networks:
      net_kafka_nifi:
        ipv4_address: 172.21.0.10


  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - zookeeper
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME : local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      net_kafka_nifi:
        ipv4_address: 172.21.0.11

  nifi:
    image: apache/nifi:1.19.0
    hostname: nifi
    ports:
      - 9443:9443
    environment:
      - NIFI_WEB_HTTPS_PORT=9443
    networks:
      net_kafka_nifi:
        ipv4_address: 172.21.0.8
#  nifi:
#    hostname: mynifi
#    image: apache/nifi:1.19.0
#    restart: on-failure
#    ports:
#      - "8443:8443" # Unsecured HTTP Web Port
#      - "8088:8080"
#    environment:
#       NIFI_WEB_HTTPS_PORT: 8083
#       NIFI_WEB_HTTP_HOST: 0.0.0.0
##      - NIFI_CLUSTER_IS_NODE=false
#       SINGLE_USER_CREDENTIALS_USERNAME: "admin"
#       SINGLE_USER_CREDENTIALS_PASSWORD: "ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB"
# #     - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
# #     - NIFI_ZK_CONNECT_STRING=zookeeper:2181
# #     - NIFI_ELECTION_MAX_WAIT=1 min
#    networks:
#      net_kafka_nifi:
#        ipv4_address: 172.21.0.7

networks:
  net_kafka_nifi:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
